baseURL = "https://gripeinst.netlify.app"
copyright = "©2020 GripEinst."
defaultContentLanguage = "en"
enableRobotsTXT = true
hasCJKLanguage = true
languageCode = "en"
theme = "hugo-notepadium"
title = "GripEinst Blog"
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
codeFences = true
noClasses = false
[params]
dateFormat = "02 Jan, 2006"
logo = ""
readingTime = true
slogan = "JavaScript-free Blog"
style = "auto"
[params.assets]
css = ["css/fonts.css"]
[params.comments]
enable = false
[params.math]
enable = false
use = "katex"
[params.nav]
showCategories = true
showTags = true
[[params.nav.custom]]
title = "About"
url = "/about"
[[params.nav.custom]]
title = "Hugo"
url = "https://gohugo.io/"
[params.profile]
avatar = "https://d33wubrfki0l68.cloudfront.net/ddf49425628d8aec7523db143916b34ae1641e11/b97e8/images/gopher-side_color.svg"
bio = "Hugo is one of the most popular open-source static site generators. With its amazing speed and flexibility, Hugo makes building websites fun again."
enable = true
github = "gohugoio"
name = "gohugo"
twitter = "GoHugoIO"
[params.share]
addThisId = ""
enable = false
inlineToolId = ""
[params.syntax]
darkTheme = "dracula"
theme = "github"
use = "none"
